print ("Hola Mundo => Jorge Jacinto ==> G1")
print ("Hola Mundo => new Angel Ruiz ==> G1")
print ("Hola Mundo => Tony Valverde==> G4")
print ("Hola Mundo => Fernando Davalos ==> G3")
print ("Hola Mundo => Espinola Narcizo ==> G1")
print ("Hola Mundo => new Jorge Jacinto ==> G1")
print ("Hola Mundo => new Mauricio Lozada ==> G2")
print ("Hola Mundo => Vasque Rojas ==> G2")

print ("Hola Munde => De la Cruz Javiercito ==> G3")
